version: '3.8'
x-database-variables: &database-variables
  MONGO_INITDB_ROOT_USERNAME: hiran
  MONGO_INITDB_ROOT_PASSWORD: secret

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      <<: *database-variables
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo_data: